const HomeStyle = {
  container: {
    flex: 1,
    backgroundColor: "#e4fbfb",
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 20,
    alignItems: "center",
    marginLeft: 15,
    marginRight: 15,
  },
  userImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 3,
    borderColor: "#62b6cb",
    marginBottom: 10,
  },
  logoutIcon: {
    position: "absolute",
    top: 10,
    right: 10,
    padding: 10,
    backgroundColor: "#fff",
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  editIcon: {
    position: "absolute",
    top: 10,
    right: 50, // Adjust the distance to position the Edit button next to the Logout button
    padding: 10,
    backgroundColor: "#fff",
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  toggleIcon: {
    position: "absolute",
    top: 50,
    right: 20,
    padding: 10,
    backgroundColor: "#fff",
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  supervisorSection: {
    marginTop: 20,
  },
  supervisorHeading: {
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 10,
  },
  supervisorBox: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
    paddingVertical: 8,
  },
  userInfo: {
    alignItems: "center",
  },
  userName: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#333",
  },
  userSubtitle: {
    fontSize: 16,
    color: "#555",
    fontStyle: "italic",
    marginBottom: 5,
  },
  userLocation: {
    fontSize: 14,
    color: "#1e6091",
    fontWeight: "600",
    marginBottom: 10,
  },
  infoBox: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
    paddingVertical: 8,
  },
  infoLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#555",
  },
  infoText: {
    fontSize: 14,
    color: "#333",
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
    backgroundColor: "#a0c7ff",
    paddingVertical: 10,
    borderRadius: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
  },
  membershipPlan: {
    marginLeft: 15,
    marginRight: 15,
  },
  financialSummaryContainer: {
    marginTop: 20,
    marginLeft: 15,
    marginRight: 15,
  },
  financialSummaryTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
    backgroundColor: "#a0c7ff",
    paddingVertical: 10,
    borderRadius: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
  },
  financialSummary: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
  },
  summaryItem: {
    alignItems: "center",
    flex: 1,
    marginHorizontal: 2,
  },
  financialCard: {
    padding: 20,
    height: 130,
    justifyContent: "center",
    alignItems: "center",
  },
  summaryValue: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
  },
  summaryLabel: {
    fontSize: 12,
    color: "#777",
    textAlign: "center",
  },

  menuContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
    marginBottom: 30,
    paddingHorizontal: 10,
  },
  menuItem: {
    alignItems: "center",
    flex: 1,
  },
  menu: {
    width: 60,
    height: 60,
    borderRadius: 45,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ddd",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  iconImage: {
    width: 30,
    height: 30,
    resizeMode: "contain",
  },
  iconLabel: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#333",
  },
  submenu: {
    width: 130,
    position: "absolute",
    top: 70,
    backgroundColor: "#fff",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
    zIndex: 1,
  },
  submenuItem: {
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  submenuText: {
    fontSize: 14,
    color: "#333",
  },
};

export default HomeStyle;
