const Profile = {
  container: {
    flex: 1,
    backgroundColor: "#e4fbfb",
    padding: 10,
  },
  topBar: {
    flexDirection: "row",
    justifyContent: "flex-end",
    paddingHorizontal: 10,
    paddingTop: 10,
  },
  stepIndicatorContainer: {
    marginTop: 20,
  },
  homeButton: {
    backgroundColor: "#000",
    paddingVertical: 5,
    paddingHorizontal: 5,
    borderRadius: 20,
  },
  content: {
    flex: 1,
    marginTop: 20,
  },
  error: {
    color: "red",
    backgroundColor: "#ffebee",
    padding: 10,
    borderRadius: 5,
    marginVertical: 10,
    textAlign: "center",
    fontWeight: "500",
  },
  success: {
    color: "green",
    backgroundColor: "#e8f5e9",
    padding: 10,
    borderRadius: 5,
    marginVertical: 10,
    textAlign: "center",
    fontWeight: "500",
  },
  header: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
  },
  imageContainer: {
    alignItems: "center",
    margin: 20,
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
  },
  uploadButton: {
    backgroundColor: "#e0e0e0",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    margin: 20,
  },
  uploadText: {
    color: "#333",
  },
  subSectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginVertical: 15,
    textAlign: "center",
  },
  description: {
    fontSize: 14,
    color: "#666",
    marginBottom: 10,
    textAlign: "center",
  },
  switchContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 10,
    marginVertical: 10,
  },
  switchLabel: {
    fontSize: 16,
  },
  safeContainer: {
    flex: 1,
  },
  contentContainer: {
    flex: 1,
    position: "relative",
  },
  subtitle: {
    fontSize: 14,
    color: "#666",
    marginBottom: 10,
    textAlign: "center",
  },
  scrollContent: {
    padding: 10,
    paddingBottom: 40,
  },
  sectionContainer: {
    marginBottom: 20,
  },
  sectionHeader: {
    fontSize: 16,
    fontWeight: "600",
    color: "#555",
    marginBottom: 10,
    paddingBottom: 5,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  itemButton: {
    flex: 1,
    margin: 5,
    padding: 15,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ccc",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "45%",
  },
  selectedButton: {
    backgroundColor: "#000",
    borderColor: "#000",
  },
  itemText: {
    color: "#333",
    textAlign: "center",
  },
  selectedText: {
    color: "#fff",
    textAlign: "center",
  },
  loadMoreButton: {
    flex: 1,
    margin: 5,
    padding: 15,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#007bff",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "90%",
    backgroundColor: "rgba(0, 123, 255, 0.1)",
  },
  loadMoreText: {
    color: "#007bff",
    fontSize: 16,
  },
  noItem: {
    color: "#888",
    fontStyle: "italic",
    marginBottom: 10,
    textAlign: "center",
  },
  zoneBox: {
    flex: 1,
    margin: 5,
    padding: 15,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ccc",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "45%",
  },
  selectedZoneBox: {
    backgroundColor: "#000",
    borderColor: "#000",
  },
  slotBox: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 10,
    padding: 15,
    marginBottom: 12,
    backgroundColor: "#fff",
    elevation: 1,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 1 },
  },
  selectedSlotBox: {
    borderColor: "#007bff",
    backgroundColor: "#e6f0ff",
  },
  specialSlotBox: {
    borderColor: "#ff9800",
    backgroundColor: "#fff3e0",
  },
  slotHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  specialNote: {
    fontSize: 12,
    color: "#ff9800",
    fontWeight: "bold",
    marginLeft: 8,
  },
  slotTime: {
    fontSize: 14,
    color: "#444",
    marginBottom: 4,
  },
  statusText: {
    marginTop: 6,
    fontSize: 12,
    fontWeight: "600",
  },
  selectedSlotText: {
    color: "#007bff",
  },
  unselectedSlotText: {
    color: "#888",
  },
  daySection: {
    marginBottom: 15,
    backgroundColor: "#f9f9f9",
    borderRadius: 8,
    padding: 12,
  },
  dayTitle: {
    fontWeight: "bold",
    fontSize: 16,
    marginBottom: 8,
  },
  row: {
    flexDirection: "column",
    marginBottom: 12,
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 8,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
  },
  pickerContainer: {
    marginVertical: 4,
    backgroundColor: "#F3F6F9",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#BDBDBD",
    overflow: "hidden",
  },
  addBtnTab: {
    marginBottom: 10,
    backgroundColor: "#4caf50",
    paddingVertical: 10,
    borderRadius: 8,
    marginHorizontal: 16,
    marginTop: 8,
    alignItems: "center",
    elevation: 2,
  },
  removeBtn: {
    backgroundColor: "#f44336",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginTop: 8,
    alignSelf: "flex-end",
  },
  removeBtnText: { color: "#fff", fontWeight: "bold" },
  picker: {
    width: "100%",
    color: "#222",
    fontSize: 16,
  },
  pickerItem: {
    fontSize: 16,
    color: "#222",
    fontWeight: "normal",
  },
  selectedPickerItem: {
    fontSize: 16,
    color: "#1976D2", // or "#388E3C" for time slot picker
    fontWeight: "bold",
    backgroundColor: "#E3F2FD",
  },
  helperText: {
    fontSize: 13,
    color: "#666",
    textAlign: "center",
    marginTop: 6,
    marginBottom: 2,
    fontWeight: "bold",
  },
  tabBarWrapper: {
    marginHorizontal: 0,
    marginTop: 10,
    marginBottom: 5,
  },
  tabBar: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingHorizontal: 8,
    gap: 8, // More space between tabs
  },
  tab: {
    flexGrow: 1,
    paddingVertical: 7,
    alignItems: "center",
    borderColor: "transparent",
    borderRadius: 8,
    elevation: 1,
    borderBottomColor: "#1976D2",
    backgroundColor: "#fff",
  },
  activeTab: {
    borderBottomWidth: 3,
    borderBottomColor: "#1976D2",
    backgroundColor: "#fff",
    borderColor: "#1976D2",
    elevation: 2,
    shadowColor: "#1976D2",
  },
  tabText: {
    fontSize: 15,
    color: "#555",
    fontWeight: "500",
  },
  activeTabText: {
    color: "#1976D2",
    fontWeight: "bold",
  },
  categoryGroup: {
    marginBottom: 20,
  },
  parentTitle: {
    fontWeight: "bold",
    fontSize: 16,
    paddingVertical: 15,
    borderTopWidth: 1,
    borderTopColor: "#eee",
  },
  itemsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  subItemButton: {
    width: "48%",
    minHeight: 60,
    marginBottom: 10,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ccc",
    alignItems: "center",
    justifyContent: "center",
  },
  parentName: {
    color: "#007AFF",
    fontWeight: "bold",
  },
  addButton: {
    backgroundColor: "#e0e0e0",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    marginBottom: 15,
  },
  addButtonText: {
    color: "#333",
  },
  removeButton: {
    position: "absolute",
    top: 5,
    right: 5,
    backgroundColor: "red",
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  removeButtonText: {
    color: "white",
    fontWeight: "bold",
  },
  note: {
    fontSize: 14,
    color: "#666",
    marginBottom: 15,
  },
  whatsappButton: {
    backgroundColor: "#25D366",
    padding: 15,
    borderRadius: 5,
    alignItems: "center",
    marginVertical: 15,
  },
  whatsappButtonText: {
    color: "white",
    fontWeight: "bold",
  },
  agreementContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#000",
    marginRight: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  checkedBox: {
    backgroundColor: "#000",
  },
  checkmark: {
    color: "#fff",
    fontWeight: "bold",
  },
  agreementText: {
    flex: 1,
    fontSize: 14,
  },
  galleryList: {
    paddingVertical: 10,
    paddingHorizontal: 5,
  },
  galleryImageContainer: {
    marginRight: 10,
    position: "relative",
  },
  galleryImage: {
    width: 100,
    height: 100,
    borderRadius: 8,
    backgroundColor: "#f0f0f0",
  },
  innerContent: {
    paddingVertical: 20,
    justifyContent: "center",
  },
  required: {
    color: "red",
  },
  documentField: {
    marginBottom: 20,
    padding: 12,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    backgroundColor: "#ffffff",
  },
  documentLabel: {
    fontSize: 16,
    marginBottom: 8,
    fontWeight: "600",
    color: "#333",
  },
  selectButton: {
    backgroundColor: "#0d6efd",
    padding: 12,
    borderRadius: 5,
    alignItems: "center",
  },
  selectButtonText: {
    color: "#fff",
  },
  previewBox: {
    marginTop: 12,
    alignItems: "center",
    padding: 10,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 6,
    backgroundColor: "#d9d9d9",
    minHeight: 110,
    justifyContent: "center",
  },
  imagePreview: {
    width: 100,
    height: 100,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ccc",
  },
  pdfLink: {
    fontSize: 16,
    color: "#007bff",
    textDecorationLine: "underline",
  },
  overlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.7)", // Darker semi-transparent background
  },
  loadingContainer: {
    backgroundColor: "transparent", // Make container transparent
    padding: 20,
    borderRadius: 10,
    alignItems: "center",
    width: "80%", // Take up most of screen width
  },
  loadingText: {
    marginTop: 20,
    fontSize: 16,
    color: "#ffffff", // White text
    textAlign: "center",
  },
};

export default Profile;
