const TransactionStyle = {
  container: {
    flex: 1,
    backgroundColor: "#e4fbfb",
    paddingTop: 20,
  },
  filterTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
    color: "#333",
  },
  dateTimeContainer: {
    alignItems: "center",
    marginBottom: 20,
  },
  dateTimeButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
    padding: 12,
    borderRadius: 8,
    width: "100%",
    justifyContent: "space-between",
    elevation: 2,
  },
  dateTimeText: {
    fontSize: 16,
    color: "#333",
    flex: 1,
  },
  icon: {
    width: 22,
    height: 22,
    tintColor: "#24a0ed",
  },
  label: {
    fontSize: 16,
    marginBottom: 5,
    color: "#555",
  },
  applyButton: {
    backgroundColor: "#ff4081",
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 15,
  },
  applyButtonText: {
    color: "#fff",
    fontSize: 16,
    textAlign: "center",
  },
  itemList: {
    paddingHorizontal: 20,
  },
  item: {
    backgroundColor: "#fff",
    padding: 15,
    borderRadius: 8,
    marginVertical: 8,
    elevation: 3,
  },
  itemType: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
  },
  itemAmount: {
    fontSize: 14,
    color: "#24a0ed",
    marginVertical: 5,
  },
  itemStatus: {
    fontSize: 12,
    color: "#4caf50",
  },
  itemDate: {
    fontSize: 12,
    color: "#777",
  },
  filteredNote: {
    textAlign: "center",
    fontSize: 16,
    fontWeight: "bold",
    color: "blue",
    marginBottom: 10,
  },
  noItems: {
    textAlign: "center",
    fontSize: 16,
    fontWeight: "bold",
    color: "#777",
    marginTop: 20,
  },
  filterContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 10,
    backgroundColor: "#fff",
    borderRadius: 30,
    marginHorizontal: 20,
    marginTop: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  filterButton: {
    backgroundColor: "#ff4081",
    padding: 10,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    width: 40,
    height: 40,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  resetButton: {
    backgroundColor: "#808080",
    padding: 10,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    width: 40,
    height: 40,
    marginLeft: 10,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  filterIcon: { width: 30, height: 30, tintColor: "#fff" },
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 10,
    width: "80%",
    elevation: 5,
  },
  closeButton: {
    alignSelf: "flex-end",
    padding: 5,
  },
  closeText: {
    fontSize: 22,
    color: "#ff4081",
  },
};

export default TransactionStyle;
